version: '3.9'

services:
  postgresql:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb 
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    env_file:
      - ./pgsql.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql

volumes:
  pg-data: